[package]
name = "pizza-analysis-morfologik"
version = "0.1.0"
authors = ["INFINI Labs <hello@infini.ltd>"]
edition = "2021"
license = "MIT"
description = "Polish and Ukrainian dictionary-based lemmatization plugin for INFINI Pizza"
repository = "https://pizza.rs"
keywords = ["pizza", "polish", "ukrainian", "lemmatizer", "morfologik"]


[features]
default = ["polish"]
polish = []
ukrainian = []
std = ["pizza-engine/std"]

[dependencies]
pizza-engine = { path = "../../lib/engine", default-features = false }
hashbrown = { version = "0.14", default-features = false }
once_cell = { version = "1", default-features = false, features = ["alloc"] }

[dev-dependencies]
